name: Run Tests
# on: [push, pull_request]
on:
  push:
    branches:
      - Test # Adjust if you want deployments for a different branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run test
      - run: npm run test:cov
